#!/bin/bash

# Script para configurar variables de entorno en Vercel después del deploy
# Este script genera los comandos que necesitas ejecutar

echo "🔧 CONFIGURACIÓN DE VARIABLES EN VERCEL"
echo "========================================"
echo ""

# Leer variables del .env.local
source .env.local

echo "📋 Opción 1: Via Vercel CLI (Automático)"
echo ""
echo "Ejecuta estos comandos uno por uno:"
echo ""
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL production"
echo "${NEXT_PUBLIC_SUPABASE_URL}"
echo ""
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production"
echo "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
echo ""
echo "vercel env add DATABASE_URL production"
echo "${DATABASE_URL}"
echo ""
echo "vercel env add TELEGRAM_BOT_TOKEN production"
echo "${TELEGRAM_BOT_TOKEN}"
echo ""
echo "vercel env add TELEGRAM_WEBHOOK_SECRET production"
echo "${TELEGRAM_WEBHOOK_SECRET}"
echo ""
echo "vercel env add TELEGRAM_CHAT_ID production"
echo "${TELEGRAM_CHAT_ID}"
echo ""
echo "vercel env add API_FOOTBALL_KEY production"
echo "${API_FOOTBALL_KEY}"
echo ""
echo ""
echo "📱 Opción 2: Via Dashboard (Manual)"
echo ""
echo "1. Ve a: https://vercel.com/tu-usuario/betpredict/settings/environment-variables"
echo "2. Agrega estas 7 variables:"
echo ""
echo "   NEXT_PUBLIC_SUPABASE_URL = ${NEXT_PUBLIC_SUPABASE_URL}"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY = ${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
echo "   DATABASE_URL = ${DATABASE_URL}"
echo "   TELEGRAM_BOT_TOKEN = ${TELEGRAM_BOT_TOKEN}"
echo "   TELEGRAM_WEBHOOK_SECRET = ${TELEGRAM_WEBHOOK_SECRET}"
echo "   TELEGRAM_CHAT_ID = ${TELEGRAM_CHAT_ID}"
echo "   API_FOOTBALL_KEY = ${API_FOOTBALL_KEY}"
echo ""
echo "3. IMPORTANTE: Después de agregar variables, ejecuta:"
echo "   vercel --prod"
echo ""
